# The objective is to perform VSTESTV2 With RerunOptions_OrderedTestOnCodedUITest_Distributed

trigger:
- master
jobs:
- job: RunTest1
  displayName: 'Run Tests'
  pool: Din_pool
  steps:              
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Visual Studio Test Platform Installer'
    inputs:
      versionSelector: 'specificVersion'
      testPlatformVersion: '15.9.0'
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      TestCaseFilter: Priority = 2
      testAssemblyVer2: 'OrderedTest1.orderedtest'
      vsTestVersion: 'toolsInstaller'
      batchingBasedOnAgentsOption: 'customBatchSize'
      configuration: '$(BuildConfiguration)'
      customBatchSizeValue: '10'
      rerunFailedTests: true
      rerunType: 'basedOnTestFailureCount'
      basedOnTestFailureCount: '5'
      rerunMaxAttempts: '3'
